import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// Temporary service to seed the wonders/ collection in Firestore.
/// DELETE THIS FILE after seeding is complete.
class SeedMigrationService {
  static final _db = FirebaseFirestore.instance;

  static Future<void> seedWondersToFirestore() async {
    final wonders = _buildSeedWonders();
    final batch = _db.batch();

    for (final w in wonders) {
      final id = w['id'] as String;
      final docRef = _db.collection('wonders').doc(id);
      w.remove('id');
      w['status'] = 'ready';
      w['source'] = 'seed';
      w['createdAt'] = DateTime.now().toUtc().toIso8601String();
      batch.set(docRef, w, SetOptions(merge: true));
    }

    await batch.commit();
    debugPrint('[SeedMigration] Seeded ${wonders.length} wonders to wonders/');
  }

  static List<Map<String, dynamic>> _buildSeedWonders() {
    return [
      {
        'id': 'marble_caves_patagonia',
        'category': 'place',
        'emotion': 'awe',
        'title': 'The Marble Caves of Patagonia',
        'subtitle': 'Where water carved cathedral walls from stone',
        'story': 'Deep in the glacial waters of General Carrera Lake, on the border between Chile and Argentina, nature has spent six thousand years sculpting one of the most surreal landscapes on Earth. The Marble Caves — known locally as Cuevas de Mármol — are a labyrinth of swirling blue and grey stone, polished by centuries of wave action into shapes that look almost intentionally designed.\n\nThe caves can only be reached by boat, and the experience of gliding into them is nothing short of otherworldly. Sunlight filters through the turquoise water and bounces off the marble walls, creating shifting patterns of blue and silver that seem to breathe with the rhythm of the lake. The color changes with the seasons and the water level, meaning no two visits are ever the same.\n\nGeologists believe the formations began taking shape around 6,000 years ago, carved by the persistent lapping of calcium-rich waters against the peninsula\'s marble bedrock. The result is a series of caverns, tunnels, and overhangs that twist and curve like the interior of a frozen wave.\n\nDespite their extraordinary beauty, the Marble Caves remain relatively unknown outside of South America. The remote location — hours from the nearest city — has kept mass tourism at bay, preserving the silence and stillness that makes the place so powerful.',
        'curiositySpark': 'The caves change color throughout the year — from deep blue in summer to turquoise in spring — depending on the water level of the glacial lake.',
        'place': {'name': 'Marble Caves', 'country': 'Chile', 'region': 'Aysén', 'lat': -46.66, 'lon': -72.62},
        'tags': ['marble', 'caves', 'patagonia', 'glacial', 'geology'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'fire_walkers_nestinarstvo',
        'category': 'tradition',
        'emotion': 'sacred',
        'title': 'The Fire Walkers of Nestinarstvo',
        'subtitle': 'Dancing barefoot on embers to honor the saints',
        'story': 'In the villages of the Strandzha Mountains in southeastern Bulgaria, an ancient ritual survives that defies both logic and pain. Nestinarstvo — the practice of dancing barefoot on glowing embers — is performed annually on the feast day of Saints Constantine and Helena, a tradition so old that no one is quite sure where Christianity ends and paganism begins.\n\nThe nestinari, as the dancers are called, enter a trance-like state induced by the rhythmic beating of a large drum called a tapan and the wailing melody of a gaida, the Bulgarian bagpipe. They carry icons of the saints as they step onto a bed of smoldering coals, their bare feet seemingly immune to the heat that would blister ordinary skin in seconds.\n\nScientists have attempted to explain the phenomenon through the physics of heat transfer and the Leidenfrost effect, but locals dismiss such explanations. For them, the fire walk is a matter of faith — a communion between the dancer and the divine that transcends the physical world.\n\nIn 2009, UNESCO inscribed Nestinarstvo on its Representative List of the Intangible Cultural Heritage of Humanity, recognizing it as one of Europe\'s most remarkable surviving rituals.',
        'curiositySpark': 'The nestinari dancers show no signs of burns despite walking on coals reaching temperatures of over 500°C.',
        'place': {'name': 'Balgari Village', 'country': 'Bulgaria', 'region': 'Strandzha', 'lat': 42.07, 'lon': 27.74},
        'tags': ['fire-walking', 'ritual', 'bulgaria', 'UNESCO', 'trance'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'blue_tea_butterfly_pea',
        'category': 'taste',
        'emotion': 'mystery',
        'title': 'The Blue Tea of Butterfly Pea',
        'subtitle': 'A Southeast Asian flower that brews into liquid sapphire',
        'story': 'In the humid lowlands of Southeast Asia, a climbing vine called Clitoria ternatea produces flowers of such intense blue that they look almost artificial. Known commonly as butterfly pea, this plant has been used for centuries in Thai, Malay, and Burmese cooking — not for its flavor, which is mild and earthy, but for its extraordinary color.\n\nWhen steeped in hot water, the dried flowers release a vivid indigo pigment that turns the liquid a deep, electric blue. The tea is striking enough on its own, but the real magic happens when you add a squeeze of citrus. The acid reacts with the anthocyanin pigments and the blue shifts instantly to purple, then to pink — a natural pH indicator disguised as a beverage.\n\nIn Bangkok\'s street markets, butterfly pea tea is served over ice with honey and lime, the color swirling and changing as the ingredients mix. In upscale cocktail bars from London to New York, bartenders use it to create drinks that shift hue before the customer\'s eyes.\n\nBeyond its beauty, the flower has a long history in Ayurvedic medicine, where it is used to improve memory and reduce anxiety. Modern research has begun to validate some of these claims, finding that the anthocyanins possess antioxidant and anti-inflammatory properties.',
        'curiositySpark': 'Adding a few drops of lemon juice to butterfly pea tea instantly changes it from deep blue to vivid purple — it\'s a natural pH indicator.',
        'place': {'name': 'Bangkok', 'country': 'Thailand', 'region': 'Central Thailand', 'lat': 13.75, 'lon': 100.52},
        'tags': ['tea', 'butterfly-pea', 'color-changing', 'thailand', 'anthocyanin'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'library_of_timbuktu',
        'category': 'story',
        'emotion': 'lost_worlds',
        'title': 'The Library of Timbuktu',
        'subtitle': 'A desert city that once held more books than any place in Europe',
        'story': 'When most Europeans were still illiterate, Timbuktu was a city of scholars. At its peak in the 15th and 16th centuries, this remote Malian city at the edge of the Sahara Desert was home to one of the greatest concentrations of written knowledge in the world — hundreds of thousands of manuscripts on astronomy, medicine, law, music, and philosophy.\n\nThe manuscripts were written in Arabic and in local languages, on paper imported from Venice and on locally made parchment. They were stored in private family libraries — some containing tens of thousands of volumes — passed down through generations as the most precious of inheritances.\n\nWhen French colonizers arrived in the 19th century, they dismissed Timbuktu as a backwater, unable to believe that a sub-Saharan African city could have produced such a literary tradition. Many manuscripts were hidden — buried in desert caves, sealed in walls, tucked under floorboards — to protect them from destruction.\n\nIn 2012, when jihadist militants occupied northern Mali, a group of librarians and scholars risked their lives to smuggle roughly 350,000 manuscripts out of Timbuktu in foot lockers, donkey carts, and river boats. It was one of the greatest cultural rescue operations in modern history.',
        'curiositySpark': 'In 2012, librarians smuggled 350,000 ancient manuscripts out of Timbuktu by donkey cart and river boat to save them from destruction by militants.',
        'place': {'name': 'Timbuktu', 'country': 'Mali', 'region': 'Tombouctou', 'lat': 16.77, 'lon': -3.01},
        'tags': ['manuscripts', 'library', 'mali', 'sahara', 'rescue'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'singing_sands_gobi',
        'category': 'sound',
        'emotion': 'serenity',
        'title': 'The Singing Sands of the Gobi',
        'subtitle': 'Dunes that hum, boom, and resonate like distant organs',
        'story': 'In the heart of the Gobi Desert, near the oasis town of Dunhuang, there is a crescent-shaped dune called Mingsha Shan — the Mountain of Singing Sand. When the wind blows across its surface, or when a person slides down its face, the sand emits a deep, resonant hum that can be heard for miles.\n\nThe sound has been described as everything from a distant foghorn to a Tibetan singing bowl to the low drone of a cathedral organ. Marco Polo, who passed through the region in the 13th century, wrote of spirits in the desert that produced music to lure travelers off their path.\n\nScientists now understand that the singing is caused by the avalanching of dry, rounded grains of quartz. As the grains cascade down the slope, they vibrate at a resonant frequency determined by the size and shape of the grains, the moisture content, and the angle of the dune face.\n\nWhat makes Mingsha Shan remarkable is the volume and clarity of its sound. While many deserts around the world have singing or booming dunes, few produce tones as pure and sustained as those heard here. On a quiet evening, the hum of the sand merges with the silence of the desert in a way that feels less like a natural phenomenon and more like the earth itself is breathing.',
        'curiositySpark': 'The booming sound of Mingsha Shan can reach up to 105 decibels — as loud as a rock concert — and was described by Marco Polo as the music of desert spirits.',
        'place': {'name': 'Khongoryn Els', 'country': 'Mongolia', 'region': 'Gobi', 'lat': 43.74, 'lon': 104.00},
        'tags': ['singing-sand', 'desert', 'gobi', 'acoustics', 'dunes'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'wangari_maathai_green_belt',
        'category': 'person',
        'emotion': 'awe',
        'title': 'Wangari Maathai and the Green Belt',
        'subtitle': 'The woman who planted 51 million trees to save a nation',
        'story': 'In 1977, a Kenyan biologist named Wangari Maathai did something that seemed impossibly simple: she planted seven trees in her backyard. From that act grew the Green Belt Movement, an organization that would eventually plant over 51 million trees across Kenya and inspire similar movements around the world.\n\nMaathai understood what many policymakers did not — that environmental destruction and poverty were two sides of the same coin. As Kenya\'s forests were cleared for commercial agriculture, rural women lost access to firewood, clean water, and fertile soil. By organizing women to plant trees, Maathai addressed all three problems simultaneously.\n\nThe Kenyan government under Daniel arap Moi saw her work as a threat. She was beaten, jailed, and publicly ridiculed. When she opposed a plan to build a skyscraper in Nairobi\'s Uhuru Park, she was called a madwoman. She persisted anyway.\n\nIn 2004, Wangari Maathai became the first African woman to receive the Nobel Peace Prize. The committee cited her contribution to sustainable development, democracy, and peace. She continued her work until her death in 2011, leaving behind a legacy that is literally rooted in the earth.',
        'curiositySpark': 'Wangari Maathai was the first African woman to win the Nobel Peace Prize, awarded for planting over 51 million trees through her Green Belt Movement.',
        'place': {'name': 'Nairobi', 'country': 'Kenya', 'region': 'Nairobi County', 'lat': -1.29, 'lon': 36.82},
        'tags': ['trees', 'activism', 'nobel-prize', 'kenya', 'environment'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'door_to_hell_darvaza',
        'category': 'place',
        'emotion': 'mystery',
        'title': 'The Door to Hell of Darvaza',
        'subtitle': 'A gas crater that has burned continuously since 1971',
        'story': 'In the middle of the Karakum Desert in Turkmenistan, there is a hole in the earth that has been on fire for over fifty years. Known locally as the "Door to Hell," the Darvaza gas crater is a 70-meter-wide pit of perpetual flame, glowing orange against the black desert night like a wound in the planet\'s surface.\n\nThe crater was created in 1971 when a Soviet drilling rig accidentally punched into a massive underground natural gas cavern. The ground beneath the rig collapsed, creating the pit and releasing enormous quantities of methane. Fearing that the gas would poison nearby villages, engineers decided to set it alight, expecting it to burn off within a few weeks.\n\nIt has been burning ever since.\n\nThe sight is both terrifying and mesmerizing. Hundreds of small flames dance across the crater floor, fed by gas seeping through cracks in the earth. The heat is intense enough to be felt from the rim, and the roar of the flames carries across the silent desert. At night, the glow is visible for miles.\n\nIn 2010, Turkmenistan\'s president ordered the crater sealed to stop the waste of natural gas, but as of today, no action has been taken. The Door to Hell remains open.',
        'curiositySpark': 'Soviet engineers lit the Darvaza crater expecting it to burn out in weeks. It has been burning continuously for over 50 years.',
        'place': {'name': 'Darvaza', 'country': 'Turkmenistan', 'region': 'Karakum Desert', 'lat': 40.25, 'lon': 58.44},
        'tags': ['crater', 'fire', 'turkmenistan', 'gas', 'desert'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'mud_mosque_djenne',
        'category': 'tradition',
        'emotion': 'wild',
        'title': 'The Mud Mosque of Djenné',
        'subtitle': 'The largest mud-brick structure on Earth, rebuilt every year by hand',
        'story': 'Every spring, the entire population of Djenné, a small city in central Mali, gathers for the Crépissage — a festival of collective labor in which thousands of people replaster the Great Mosque with fresh mud. It is the largest mud-brick building in the world, and it requires this annual ritual to survive.\n\nThe mosque was first built in the 13th century, though the current structure dates to 1907. Its walls are made of sun-baked earth bricks called ferey, held together with a mortar of sand and mud. The wooden beams that protrude from the walls — called toron — serve as permanent scaffolding for the annual replastering.\n\nThe Crépissage is not merely maintenance; it is a celebration. Music fills the streets, food is shared, and the work itself becomes a kind of dance, with teams of men hauling buckets of mud up the walls while women and children prepare the mixture below.\n\nUNESCO listed Djenné as a World Heritage Site in 1988, but the mosque\'s survival depends not on international recognition but on the willingness of ordinary people to show up, year after year, and rebuild what time and weather have worn away.',
        'curiositySpark': 'Every year, the entire city of Djenné participates in replastering the Great Mosque by hand — the world\'s largest mud-brick building.',
        'place': {'name': 'Djenné', 'country': 'Mali', 'region': 'Mopti', 'lat': 13.91, 'lon': -4.56},
        'tags': ['mosque', 'mud-brick', 'mali', 'UNESCO', 'communal'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'bioluminescent_bays_vieques',
        'category': 'place',
        'emotion': 'serenity',
        'title': 'The Bioluminescent Bays of Vieques',
        'subtitle': 'Waters that glow electric blue with every movement',
        'story': 'On the southern shore of Vieques, a small island off the coast of Puerto Rico, there is a bay that glows in the dark. Mosquito Bay — despite its unfortunate name — is the brightest bioluminescent bay in the world, a place where every stroke of a paddle, every movement of a fish, every drop of rain triggers a burst of blue-green light.\n\nThe glow is produced by dinoflagellates — microscopic organisms called Pyrodinium bahamense that emit light when disturbed. Mosquito Bay contains up to 700,000 of these organisms per gallon of water, a concentration so dense that the effect is visible even on moonlit nights.\n\nThe conditions that create this phenomenon are remarkably specific. The bay is shallow, warm, and sheltered, with a narrow channel connecting it to the ocean. Red mangroves line the shore, their decaying leaves providing the vitamin B12 that the dinoflagellates need to survive.\n\nSwimming in the bay at night is an experience that borders on the hallucinatory. Your body becomes outlined in light. Drops of water from your fingers leave trails of blue. Fish dart away in streaks of electric neon.',
        'curiositySpark': 'Mosquito Bay in Vieques contains up to 700,000 bioluminescent organisms per gallon of water — the highest concentration ever recorded.',
        'place': {'name': 'Mosquito Bay', 'country': 'Puerto Rico', 'region': 'Vieques', 'lat': 18.09, 'lon': -65.44},
        'tags': ['bioluminescence', 'bay', 'puerto-rico', 'dinoflagellates', 'night'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'salt_harvests_maras',
        'category': 'taste',
        'emotion': 'sacred',
        'title': 'The Salt Harvests of Maras',
        'subtitle': 'Inca salt terraces still feeding families after 600 years',
        'story': 'High in the Sacred Valley of Peru, at an altitude of 3,380 meters, a mountainside is covered in thousands of shallow white pools that cascade down the slope like a giant staircase. These are the salt pans of Maras — and they have been in continuous use since before the Inca Empire.\n\nA natural spring near the top of the slope produces water with an extraordinarily high salt content. This water is channeled through an intricate network of hand-cut stone channels into the terraced pools below. As the water evaporates in the thin mountain air, it leaves behind crystals of pink-tinged salt.\n\nEach pool is owned and maintained by a single family, and the rights are passed down through generations. During harvest season, families wade into the knee-deep pools and rake the crystallized salt to the edges, where it dries in the sun before being collected.\n\nThe salt of Maras has a distinctive mineral flavor that has made it prized by chefs around the world. It contains traces of calcium, magnesium, and iron that give it a complexity absent from industrial table salt.',
        'curiositySpark': 'The salt terraces of Maras have been continuously operated by local families for over 600 years, predating the Inca Empire itself.',
        'place': {'name': 'Maras', 'country': 'Peru', 'region': 'Sacred Valley', 'lat': -13.36, 'lon': -72.16},
        'tags': ['salt', 'terraces', 'peru', 'inca', 'harvest'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'whispering_gallery_st_pauls',
        'category': 'sound',
        'emotion': 'mystery',
        'title': 'The Whispering Gallery of St Paul\'s',
        'subtitle': 'Where a whisper travels 34 meters across a cathedral dome',
        'story': 'Inside the dome of St Paul\'s Cathedral in London, 30 meters above the cathedral floor, there is a narrow walkway where the laws of acoustics produce something remarkable. If you press your lips to the curved wall and whisper, your words will travel along the surface of the dome and arrive, perfectly audible, at the ear of someone sitting on the opposite side — 34 meters away.\n\nThe phenomenon was first described by Lord Rayleigh in the 19th century. Sound waves hug the concave interior surface of the dome, losing very little energy as they travel, because the wall continuously reflects them inward. The effect is so efficient that a whisper — which would normally be inaudible at such a distance — arrives with startling clarity.\n\nChristopher Wren, who designed the cathedral after the Great Fire of London in 1666, may not have intended this acoustic effect, but it has become one of the building\'s most celebrated features. Visitors climb 259 steps to reach the gallery, then sit on opposite sides to test the whisper for themselves.\n\nThe same principle has been observed in other circular structures around the world — the Echo Wall of the Temple of Heaven in Beijing, the dome of the U.S. Capitol — but St Paul\'s remains the most famous example.',
        'curiositySpark': 'A whisper against the wall of St Paul\'s Whispering Gallery can be heard clearly 34 meters away on the opposite side of the dome.',
        'place': {'name': 'St Paul\'s Cathedral', 'country': 'United Kingdom', 'region': 'London', 'lat': 51.51, 'lon': -0.10},
        'tags': ['acoustics', 'cathedral', 'london', 'whisper', 'dome'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'alexandra_david_neel_lhasa',
        'category': 'person',
        'emotion': 'wild',
        'title': 'Alexandra David-Néel in Forbidden Lhasa',
        'subtitle': 'The first European woman to enter Tibet\'s holiest city',
        'story': 'In 1924, a 55-year-old French woman named Alexandra David-Néel walked into the forbidden city of Lhasa disguised as a Tibetan beggar. She had darkened her skin with cocoa and soot, braided her hair with yak tail extensions, and carried a pistol hidden beneath her robes. She was the first European woman to set foot in the city.\n\nDavid-Néel\'s journey to Lhasa was the culmination of a lifetime of extraordinary travel and spiritual seeking. Born in Paris in 1868, she had studied Sanskrit at the Sorbonne, performed as an opera singer, and traveled alone through India and Ceylon before becoming fascinated with Tibetan Buddhism.\n\nShe spent 14 years living in Asia before attempting the journey to Lhasa, during which she studied with lamas, lived in caves, and reportedly witnessed monks practicing tummo — the ability to generate intense body heat through meditation. She crossed the Himalayas in winter, surviving blizzards and bandits.\n\nHer account of the journey, "My Journey to Lhasa," became an international bestseller. She continued traveling and writing until her death in 1969 at the age of 100, having spent more time in Asia than any European woman of her era.',
        'curiositySpark': 'Alexandra David-Néel entered the forbidden city of Lhasa at age 55, disguised as a beggar with her skin darkened by cocoa and soot.',
        'place': {'name': 'Lhasa', 'country': 'China', 'region': 'Tibet', 'lat': 29.65, 'lon': 91.13},
        'tags': ['explorer', 'tibet', 'disguise', 'buddhism', 'forbidden-city'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'abandoned_island_hashima',
        'category': 'place',
        'emotion': 'lost_worlds',
        'title': 'The Abandoned Island of Hashima',
        'subtitle': 'A concrete ghost city rising from the sea off Nagasaki',
        'story': 'Fifteen kilometers off the coast of Nagasaki, a small island rises from the East China Sea like a concrete battleship. Hashima — known as Gunkanjima, or Battleship Island — was once the most densely populated place on Earth. Today, it is completely abandoned.\n\nFrom 1887 to 1974, Hashima was a coal mining facility operated by Mitsubishi. At its peak in 1959, over 5,000 people lived on an island measuring just 480 meters long and 150 meters wide. Every surface was covered in concrete: apartment blocks, schools, shops, a hospital, a cinema, even a rooftop garden.\n\nWhen petroleum replaced coal as Japan\'s primary energy source, the mine closed and the island was evacuated in just three months. The residents left behind everything — furniture, televisions, personal belongings — creating a frozen snapshot of 1970s Japanese life.\n\nToday, Hashima is a UNESCO World Heritage Site and a haunting monument to industrial ambition. The concrete buildings are slowly crumbling, reclaimed by salt wind and typhoons. Trees grow through collapsed roofs. The silence is total.',
        'curiositySpark': 'At its peak, Hashima Island had a population density of 83,500 people per square kilometer — higher than any city in the world today.',
        'place': {'name': 'Hashima Island', 'country': 'Japan', 'region': 'Nagasaki', 'lat': 32.63, 'lon': 129.74},
        'tags': ['abandoned', 'island', 'japan', 'mining', 'ghost-city'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'living_root_bridges_meghalaya',
        'category': 'tradition',
        'emotion': 'awe',
        'title': 'The Living Root Bridges of Meghalaya',
        'subtitle': 'Bridges grown from the roots of trees over generations',
        'story': 'In the wettest place on Earth — the Khasi Hills of Meghalaya, northeastern India — the War-Khasi people have been growing their bridges for centuries. Using the aerial roots of the rubber fig tree (Ficus elastica), they guide and train the roots across rivers and gorges, weaving them into living structures that strengthen with age.\n\nA single bridge takes 15 to 20 years to become functional, and the strongest ones are over 500 years old. They are maintained by entire villages, with each generation responsible for guiding new roots to reinforce the structure. The result is a bridge that is literally alive — it grows, it heals, and it gets stronger every year.\n\nThe most famous example is the Umshiang Double Decker Root Bridge near the village of Nongriat. Two bridges are stacked one above the other, connected by stone steps, spanning a river in a jungle so dense that sunlight barely reaches the forest floor.\n\nIn a region that receives over 11,000 millimeters of rain per year, conventional bridges rot and rust. But the living root bridges thrive in the moisture, their grip on the earth only deepening with each monsoon.',
        'curiositySpark': 'The living root bridges of Meghalaya take 15-20 years to grow but last for over 500 years — and they get stronger with age.',
        'place': {'name': 'Nongriat Village', 'country': 'India', 'region': 'Meghalaya', 'lat': 25.29, 'lon': 91.68},
        'tags': ['roots', 'bridges', 'india', 'meghalaya', 'living-architecture'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'voynich_manuscript',
        'category': 'story',
        'emotion': 'mystery',
        'title': 'The Voynich Manuscript',
        'subtitle': 'A 600-year-old book no one has ever been able to read',
        'story': 'In a vault at Yale University\'s Beinecke Rare Book Library lies a 240-page manuscript written in a script that no one has ever deciphered. The Voynich Manuscript, named after the Polish book dealer who purchased it in 1912, is filled with elaborate illustrations of unknown plants, astronomical diagrams, and naked human figures bathing in green liquid.\n\nRadiocarbon dating places the manuscript\'s creation between 1404 and 1438, somewhere in Central Europe. The text is written fluently from left to right in an alphabet of roughly 20-25 distinct characters, suggesting that the author wrote with confidence rather than laboriously encoding a message.\n\nCryptographers, linguists, and computer scientists have been trying to crack the Voynich script for over a century. The text shows statistical patterns consistent with natural language — word length distributions, character frequencies, even something resembling syntax — but no one has produced a convincing translation.\n\nTheories range from the mundane (a medieval health manual in a lost language) to the exotic (an alien artifact, a elaborate hoax, the work of a schizophrenic genius). The manuscript remains one of the most studied and least understood documents in human history.',
        'curiositySpark': 'Despite over a century of attempts by the world\'s best codebreakers, the Voynich Manuscript has never been deciphered — not even a single word.',
        'place': {'name': 'Yale University', 'country': 'United States', 'region': 'Connecticut', 'lat': 41.31, 'lon': -72.93},
        'tags': ['manuscript', 'mystery', 'undeciphered', 'medieval', 'yale'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'rock_churches_lalibela',
        'category': 'place',
        'emotion': 'sacred',
        'title': 'The Rock Churches of Lalibela',
        'subtitle': 'Eleven churches carved downward into solid volcanic rock',
        'story': 'In the highlands of northern Ethiopia, at an altitude of 2,500 meters, eleven medieval churches stand in the earth rather than on it. They were not built from the ground up but carved from the top down — excavated from the living rock of the mountainside, their roofs level with the surrounding terrain.\n\nAccording to Ethiopian tradition, King Lalibela ordered the churches built in the 12th century after a pilgrimage to Jerusalem. When Muslim conquests made the Holy City inaccessible to Ethiopian Christians, Lalibela set out to create a New Jerusalem in the African highlands.\n\nThe most famous of the eleven is Bete Giyorgis — the Church of St. George — a perfect cruciform structure carved from a single block of red volcanic tuff. Seen from above, it appears as a cross-shaped hole in the earth, twelve meters deep, connected to the surface only by a narrow trench.\n\nHow the churches were carved remains a matter of debate. The precision of the work — with walls, windows, columns, and drainage channels all cut from a single piece of stone — suggests engineering knowledge far beyond what was believed to exist in 12th-century Ethiopia.',
        'curiositySpark': 'The churches of Lalibela were carved downward from the surface into solid volcanic rock — Bete Giyorgis sits 12 meters below ground level.',
        'place': {'name': 'Lalibela', 'country': 'Ethiopia', 'region': 'Amhara', 'lat': 12.03, 'lon': 39.04},
        'tags': ['churches', 'rock-hewn', 'ethiopia', 'UNESCO', 'medieval'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'casu_marzu_sardinia',
        'category': 'taste',
        'emotion': 'wild',
        'title': 'The Casu Marzu of Sardinia',
        'subtitle': 'A cheese deliberately infested with live larvae',
        'story': 'On the Italian island of Sardinia, there exists a cheese so extreme that it has been banned by the European Union — and so beloved that Sardinians make it anyway. Casu marzu, which translates roughly as "rotten cheese," is a pecorino that has been deliberately infested with the larvae of the cheese fly, Piophila casei.\n\nThe process begins with a wheel of pecorino sardo, which is left outside with its rind partially removed, inviting the flies to lay their eggs inside. The larvae hatch and begin eating through the cheese, their digestive acids breaking down the fats and creating a soft, spreadable texture and a pungent, ammonia-tinged flavor.\n\nThe cheese is traditionally eaten with the larvae still alive and wriggling. Sardinian etiquette holds that if the larvae have died, the cheese has gone bad and should not be consumed. Some diners cover the cheese with one hand while eating with the other, as the larvae can jump up to 15 centimeters when disturbed.\n\nDespite its EU ban (classified as a health hazard), casu marzu remains a point of fierce cultural pride in Sardinia. It is served at weddings, festivals, and family gatherings, and it has been included in the Guinness Book of World Records as the world\'s most dangerous cheese.',
        'curiositySpark': 'Casu marzu larvae can jump up to 15 centimeters when disturbed — diners sometimes cover the cheese with their hand while eating.',
        'place': {'name': 'Sardinia', 'country': 'Italy', 'region': 'Sardinia', 'lat': 40.12, 'lon': 9.01},
        'tags': ['cheese', 'larvae', 'sardinia', 'banned', 'fermented'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'throat_singers_tuva',
        'category': 'sound',
        'emotion': 'awe',
        'title': 'The Throat Singers of Tuva',
        'subtitle': 'Singers who produce two notes simultaneously from a single voice',
        'story': 'In the remote Republic of Tuva, nestled between Siberia and Mongolia, herders have practiced a form of singing that seems physically impossible. Khoomei — Tuvan throat singing — allows a single vocalist to produce two or more distinct pitches simultaneously: a deep, rumbling drone and a high, crystalline overtone that floats above it like a flute.\n\nThe technique involves precise manipulation of the vocal cords, tongue, lips, and throat to isolate and amplify the harmonic overtones that are naturally present in every human voice but normally inaudible. The result is otherworldly — a sound that seems to come from two different sources at once.\n\nTuvan throat singing originated as an imitation of the natural world. Different styles mimic the sounds of rivers (borbangnadyr), wind across the steppe (sygyt), and the low hum of the mountains (kargyraa). For the Tuvan people, the landscape is not merely a backdrop but a living presence that speaks and can be spoken to.\n\nIn 2010, UNESCO inscribed Tuvan throat singing on its list of Intangible Cultural Heritage. Today, young Tuvans are learning the art in growing numbers, and throat singing festivals attract musicians and audiences from around the world.',
        'curiositySpark': 'Tuvan throat singers can produce two distinct notes simultaneously from a single voice — a low drone and a high overtone — by manipulating their vocal anatomy.',
        'place': {'name': 'Kyzyl', 'country': 'Russia', 'region': 'Tuva', 'lat': 51.72, 'lon': 94.45},
        'tags': ['throat-singing', 'tuva', 'overtone', 'UNESCO', 'harmonic'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'boiling_lake_dominica',
        'category': 'place',
        'emotion': 'wild',
        'title': 'The Boiling Lake of Dominica',
        'subtitle': 'A lake heated by magma to near-boiling temperatures',
        'story': 'In the Morne Trois Pitons National Park on the Caribbean island of Dominica, there is a lake that is literally boiling. The Boiling Lake is the second-largest hot spring in the world — a flooded fumarole roughly 60 meters across, filled with blue-grey water that bubbles and steams at temperatures reaching 92°C at its edges.\n\nThe lake sits in a deep volcanic crater, surrounded by sheer cliffs draped in tropical vegetation. Reaching it requires a grueling three-hour hike through the Valley of Desolation — a landscape of steaming vents, sulfur-stained rocks, and hot streams that give the impression of walking across the surface of another planet.\n\nThe center of the lake is perpetually shrouded in a cloud of steam, making it impossible to measure the temperature at the deepest point. Geologists believe the lake is heated by a magma chamber directly below, with gases and superheated water rising through fractures in the volcanic rock.\n\nThe Boiling Lake was first reported to the outside world in 1870 by two Englishmen who climbed to the crater rim and looked down into what they described as a cauldron from hell. The water level and temperature fluctuate unpredictably, and on at least two occasions the lake has drained completely, only to refill days later.',
        'curiositySpark': 'Dominica\'s Boiling Lake has drained completely at least twice and refilled — no one knows exactly why.',
        'place': {'name': 'Boiling Lake', 'country': 'Dominica', 'region': 'Morne Trois Pitons', 'lat': 15.32, 'lon': -61.30},
        'tags': ['boiling', 'volcanic', 'dominica', 'hot-spring', 'fumarole'],
        'imageUrl': '',
        'imageAttribution': '',
      },
      {
        'id': 'floating_post_office_dal_lake',
        'category': 'story',
        'emotion': 'serenity',
        'title': 'The Floating Post Office of Dal Lake',
        'subtitle': 'Mail delivered by shikara boat on a Kashmiri lake',
        'story': 'On the still waters of Dal Lake in Srinagar, Kashmir, a wooden houseboat serves as India\'s only floating post office. Moored among the lotus flowers and shikaras, it has been in operation since 1911, delivering mail to the thousands of people who live on the lake\'s houseboats.\n\nThe post office is a functioning branch of India Post, complete with its own unique postal stamp featuring a shikara boat. Letters and parcels are collected and delivered by postal workers who travel the lake\'s waterways by boat, navigating between floating gardens, houseboats, and the wooden jetties that serve as addresses.\n\nDal Lake is home to a permanent community of roughly 50,000 people who live on and around the water. Houseboats range from modest wooden structures to elaborately carved cedar vessels with English names like "Good Luck" and "Palace on the Lake" — a legacy of the British colonial era when foreigners were forbidden from owning land in Kashmir but not boats.\n\nThe floating post office has survived wars, floods, and the advent of email. It remains a beloved institution, and its stamp — available only here — is prized by philatelists around the world.',
        'curiositySpark': 'The floating post office on Dal Lake has its own unique postal stamp and has been delivering mail by boat since 1911.',
        'place': {'name': 'Dal Lake', 'country': 'India', 'region': 'Kashmir', 'lat': 34.12, 'lon': 74.84},
        'tags': ['post-office', 'floating', 'kashmir', 'houseboat', 'mail'],
        'imageUrl': '',
        'imageAttribution': '',
      },
    ];
  }
}
