// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQlVg34-VulJ-BhyyNUVEN5XCVyHynvg',
    appId: '1:244656743763:web:882d48159ad4d1c220eda6',
    messagingSenderId: '244656743763',
    projectId: 'flow-2538d',
    authDomain: 'flow-2538d.firebaseapp.com',
    storageBucket: 'flow-2538d.firebasestorage.app',
    measurementId: 'G-LLHP9T9H44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_3c5NTIqyrxdbYPfYymm-RYlkKA3zPKA',
    appId: '1:244656743763:android:788af62cc31ad3bb20eda6',
    messagingSenderId: '244656743763',
    projectId: 'flow-2538d',
    storageBucket: 'flow-2538d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARm7TEyti0TSyKSEH6omyKfDHmiF8Nw9w',
    appId: '1:244656743763:ios:569718f6780ee66720eda6',
    messagingSenderId: '244656743763',
    projectId: 'flow-2538d',
    storageBucket: 'flow-2538d.firebasestorage.app',
    androidClientId: '244656743763-400d8lj162c1sc7en2rg99uoik5aqgbu.apps.googleusercontent.com',
    iosClientId: '244656743763-9i82rkc9i3pfehg87gpfndd4ks8195c0.apps.googleusercontent.com',
    iosBundleId: 'com.flow.app',
  );

}